spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sugar?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      timeout: 10000
      database: 0
      port: 6379
      host: localhost

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

mybatis-plus:
  type-aliases-package: com.sugar.sugar.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl